analytics: {}
color:
  brandColors:
    - '#000000'
    - '#624314'
    - '#DC9700'
    - '#D03E0B'
    - '#D7BA7E'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 0.680743
name: Food
opengraph: {}
purpose: []
typography_spectrum: 0.644736
