color:
  brandColors:
    - '#B8B0C0'
    - '#802800'
    - '#907070'
    - '#FF5000'
    - '#000000'
  brandStrength: 0.97804
  lightness: 0.699324
  rhythmicContrast: 0.229729
  saturation: 0.162162
layout_spectrum: 0.680743
name: The Cutest Deers
typography_spectrum: 0.35307
