color:
  brandColors:
    - '#000000'
    - '#A84810'
    - '#788840'
    - '#B0C050'
    - '#C0D068'
  brandStrength: 0.97804
  lightness: 0.699324
  rhythmicContrast: 0.229729
  saturation: 0.162162
layout_spectrum: 0.680743
name: The Cutest Deers
typography_spectrum: 0.35307
