analytics: {}
color:
  brandColors:
    - '#000000'
    - '#A84810'
    - '#788840'
    - '#B0C050'
    - '#C0D068'
  brandStrength: 0
  lightness: 0.483552
  rhythmicContrast: 0
  saturation: 0.485745
cta: {}
layout_spectrum: 0.680743
name: Food
opengraph: {}
purpose: []
typography_spectrum: 0.644736
