analytics: {}
color:
  brandColors:
    - '#000000'
    - '#A84810'
    - '#788840'
    - '#B0C050'
    - '#C0D068'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 0.680743
name: Food
opengraph: {}
purpose: []
typography_spectrum: 0.644736
